version: '3'

services:
  ex3pg:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'ex3pg'
    restart: always
    volumes:
      - ex3pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ex3user
      POSTGRES_PASSWORD: ex3password

volumes:
  ex3pg-data:
